core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.home_view, name='home'),
    path('gallery/', views.gallery_view, name='gallery'),
    path('results/', views.result_view, name='result'),
    path('tournaments/', views.tournament_view, name='tournaments'),
    # path('tournaments/', views.tournaments_list, name='tournaments_list'),
    # path('tournaments/<int:tournament_id>/', views.tournament_detail, name='tournament_detail'),
]

management/urls.py
from django.urls import path
from . import views

app_name = 'management'

urlpatterns = [
    path('login/', views.UserLoginView.as_view(), name='admin_login'),
    path('dashboard/', views.dashboard_view, name='admin_dashboard'),
    path('past-tournaments-list/', views.past_tournament_list_view, name='admin_past_tournaments-list'),
    path('upcoming-tournaments-list/', views.upcoming_tournament_list_view, name='admin_upcoming_tournaments-list'),
    path('tournament-detail/<int:id>/', views.tournament_detail_view, name="admin_tournament_detail"),
    path('tournament-registrations/', views.tournament_registrations_view, name="admin_tournament_registration"),
    path('tournament-approval/<int:id>/', views.registration_approval_view, name="admin_tournament_approval"),
    path('tournament-players/', views.tournament_players_view, name="admin_tournament_players"),
    path('generate-id/<int:player_id>/', views.generate_id_card, name='generate_id_card'),
    path('results-list/', views.results_list_view, name="admin_result_list"),
    path('schools/', views.schools_view, name="admin_schools"),
    path('gallery-posts/', views.gallery_posts_view, name="admin_gallery"),
    path('players/', views.player_list_view, name="admin_player_list"),
    path('player-profile/<int:id>/', views.player_profile_view, name="admin_player_profile"),
    path('logout/', views.logout_view, name="admin_logout"),
    path('users/', views.users_view, name="admin_users"),
    # path('tournaments/<int:tournament_id>/approve/', views.approve_tournament_registration, name='approve_tournament_registration'),
    # path('tournaments/<int:tournament_id>/players/', views.view_tournament_players, name='view_tournament_players'),
    # path('tournaments/<int:tournament_id>/results/', views.upload_tournament_results, name='upload_tournament_results'),
]

pe_football/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include
from django.conf.urls.static import static

from pe_football import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('schools/', include('schools.urls', namespace='schools')),
    path('management/', include('management.urls', namespace='management')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

schools/urls.py
from django.urls import path
from . import views

app_name = 'schools'

urlpatterns = [
    path('register/', views.UserRegistrationView.as_view(), name='school_register'),
    path('login/', views.UserLoginView.as_view(), name='school_login'),
    path('logout/', views.user_logout_view, name='school_logout'),
    path('dashboard/', views.dashboard_view, name='school_dashboard'),
    path('upcoming-tournaments/', views.upcoming_tournaments_view, name='upcoming_tournaments'),
    path('registerd-tournaments/', views.registered_tournaments_view, name='registered_tournaments'),
    path('register-tournament/<int:id>/', views.register_tournament_view, name='register_tournament'),
    path('tournament-detail/<int:id>/', views.tournament_detail_view, name='tournament_detail'),
    path('tournament/<int:tournament_id>/register-players/', views.register_players_for_tournament_view, name='register_players_for_tournament'),
    path('player-list/', views.players_list_view, name='player_list'),
    path('players/create/', views.create_player_view, name='create_player'),
    path('player-profile/<int:id>/', views.player_profile_view, name='player_profile'),
    path('result-list/', views.results_list_view, name='result_list'),
    path('create-school-profile/', views.create_school_profile_view, name='create_school_profile'),
    # path('tournaments/<int:tournament_id>/players/', views.select_players, name='select_players'),
]

management/forms.py
from django import forms
from .models import Tournament, TournamentResults
from schools.models import SchoolProfile

STAGE_CHOICES = [
    ('Group Stage', 'Group Stage'),
    ('Quarter Final', 'Quarter Final'),
    ('Semi Final', 'Semi Final'),
    ('Round of 16', 'Round of 16'),
    ('Final', 'Final'),
]


class TournamentForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )
    venue = forms.CharField(
        max_length=255,
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )
    age_limit = forms.IntegerField(
        widget=forms.NumberInput(attrs={'class': 'form-control'})
    )
    start_date = forms.DateField(
        widget=forms.DateInput(attrs={'class': 'form-control', 'type': 'date'})
    )
    time = forms.TimeField(
        widget=forms.TimeInput(attrs={'class': 'form-control', 'type': 'time'})
    )
    participation_fee = forms.DecimalField(
        max_digits=10,
        decimal_places=2,
        widget=forms.NumberInput(attrs={'class': 'form-control'})
    )
    description = forms.CharField(

        widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 2})
    )


class TournamentResultsForm(forms.Form):
    tournament = forms.ModelChoiceField(
        queryset=Tournament.objects.all(),
        widget=forms.Select(attrs={'class': 'form-control'})
    )
    school1 = forms.ModelChoiceField(
        queryset=SchoolProfile.objects.all(),
        widget=forms.Select(attrs={'class': 'form-control'})
    )
    school2 = forms.ModelChoiceField(
        queryset=SchoolProfile.objects.all(),
        widget=forms.Select(attrs={'class': 'form-control'})
    )
    school1_score = forms.IntegerField(
        widget=forms.NumberInput(attrs={'class': 'form-control'})
    )
    school2_score = forms.IntegerField(
        widget=forms.NumberInput(attrs={'class': 'form-control'})
    )
    stage = forms.ChoiceField(
        choices=STAGE_CHOICES,
        widget=forms.Select(attrs={'class': 'form-control'})
    )


class InTournamentResultsForm(forms.Form):
    school1 = forms.ModelChoiceField(
        queryset=SchoolProfile.objects.all(),
        widget=forms.Select(attrs={'class': 'form-control'})
    )
    school2 = forms.ModelChoiceField(
        queryset=SchoolProfile.objects.all(),
        widget=forms.Select(attrs={'class': 'form-control'})
    )
    school1_score = forms.IntegerField(
        widget=forms.NumberInput(attrs={'class': 'form-control'})
    )
    school2_score = forms.IntegerField(
        widget=forms.NumberInput(attrs={'class': 'form-control'})
    )
    stage = forms.ChoiceField(
        choices=STAGE_CHOICES,
        widget=forms.Select(attrs={'class': 'form-control'})
    )


class MediaContentForm(forms.Form):
    title = forms.CharField(
        max_length=255,
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )
    youtube_url = forms.URLField(
        max_length=255,
        widget=forms.URLInput(attrs={'class': 'form-control'})
    )

    description = forms.CharField(
        widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 2})
    )
    cover_image = forms.ImageField(
        widget=forms.FileInput(attrs={'class': 'form-control'})
    )

management/views.py
from django.contrib import messages
from django.contrib.auth import logout
from django.contrib.auth.views import LoginView
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views.decorators.cache import cache_control
from .models import Tournament, TournamentResults, MediaContent
from schools.models import SchoolProfile, Player, TournamentPlayer, TournamentRegistration
from .forms import TournamentForm, TournamentResultsForm, MediaContentForm
from django import forms
from .decorators import admin_required
from django.http import HttpResponse
from django.shortcuts import get_object_or_404
from PIL import Image, ImageDraw, ImageFont
import qrcode
from reportlab.pdfgen import canvas
from io import BytesIO
from pe_football import settings
import tempfile
import os


def generate_id_card(request, player_id):
    player = get_object_or_404(Player, id=player_id)

    # Load the ID card template
    template_path = settings.BASE_DIR / settings.STATIC_CYBER / 'id.jpeg'
    template = Image.open(template_path)

    # Create a drawing context
    draw = ImageDraw.Draw(template)

    # Define a larger font size
    heading_path = settings.BASE_DIR / settings.STATIC_CYBER / 'BRLNSDB.TTF'
    font_path = settings.BASE_DIR / settings.STATIC_CYBER / 'Humanist521LightBT.ttf'
    font = ImageFont.truetype(heading_path, 32)
    name_font = ImageFont.truetype(heading_path, 44)
    heading_font = ImageFont.truetype(font_path, 40)

    # Player detailss
    player_details = {
        'photo_path': player.passport_photo.path,  # Adjust as needed
        'dob': player.date_of_birth.strftime('%Y-%m-%d'),
        'national_id': player.national_id,
        'school': player.school.name,
        'name': player.first_name + ' ' + player.last_name,
        'position': player.position
    }

    # Positions on the ID card for each detail
    positions = {
        'name': (270, 282),
        'position': (270, 285),
        'photo': (270, 380),  # x, y coordinates for the photo
        'dob': (310, 697),
        'national_id': (310, 745),
        'school': (310, 800)
    }

    # Load and place the player's photo
    player_photo = Image.open(player_details['photo_path']).resize((250, 250))
    template.paste(player_photo, positions['photo'])

    # Draw text details with larger font size
    draw.text(positions['name'], f"{player_details['name']}", font=name_font, fill="white")
    draw.text(positions['dob'], f"{player_details['dob']}", font=font, fill="white")
    draw.text(positions['national_id'], f"{player_details['national_id']}", font=font, fill="white")
    draw.text(positions['school'], f"{player_details['school']}", font=font, fill="white")

    # Generate a QR code with player details
    qr_data = f"Name: {player.first_name} {player.last_name}\nDOB: {player_details['dob']}\nNational ID: {player_details['national_id']}"
    qr = qrcode.QRCode(box_size=10, border=5)
    qr.add_data(qr_data)
    qr.make(fit=True)
    qr_img = qr.make_image(fill='black', back_color='white').convert('RGB')

    # Position and place the QR code on the ID card
    qr_position = (570, 900)  # x, y coordinates for the QR code
    qr_img = qr_img.resize((170, 170))  # Resize the QR code to fit on the card
    template.paste(qr_img, qr_position)

    # Save the ID card to a temporary file
    temp_file = tempfile.NamedTemporaryFile(delete=False, suffix='.jpeg')
    template.save(temp_file, 'JPEG')
    temp_file.close()

    # Read the temporary file and create an HTTP response with the image
    with open(temp_file.name, 'rb') as f:
        image_data = f.read()

    # Clean up the temporary file
    os.unlink(temp_file.name)

    response = HttpResponse(image_data, content_type='image/jpeg')
    response['Content-Disposition'] = f'inline; filename="{player.first_name}_{player.last_name}_id_card.jpeg"'

    return response


STAGE_CHOICES = [
    ('Group Stage', 'Group Stage'),
    ('Quarter Final', 'Quarter Final'),
    ('Semi Final', 'Semi Final'),
    ('Round of 16', 'Round of 16'),
    ('Final', 'Final'),
]


class UserLoginView(LoginView):
    template_name = 'management/user_login.html'

    def get_success_url(self):
        return reverse_lazy('management:admin_upcoming_tournaments-list')


@admin_required()
def dashboard_view(request):
    context = {}
    return render(request, 'management/manager_dash.html', context)


@admin_required()
def player_list_view(request):
    context = {
        'players': Player.objects.all(),
    }
    return render(request, 'management/player_list.html', context)


@admin_required()
def player_profile_view(request, id):
    player = Player.objects.filter(id=id).first()
    tournaments = TournamentPlayer.objects.filter(player=player).select_related('tournament')
    played_tournaments = [tp.tournament for tp in tournaments]
    context = {
        'player': player,
        'tournaments': tournaments
    }
    return render(request, 'management/player_profile.html', context)


@admin_required()
def upcoming_tournament_list_view(request):
    if request.method == "POST":
        form = TournamentForm(request.POST)
        if form.is_valid():
            tournament = Tournament.objects.create(
                name=form.data['name'],
                start_date=form.data['start_date'],
                venue=form.data['venue'],
                description=form.data['description'],
                time=form.data['time'],
                participation_fee=form.data['participation_fee'],
                age_limit=form.data['age_limit']
            )
            tournament.save()
            return redirect('management:admin_upcoming_tournaments-list')
        else:
            messages.error(request, form.errors)

    else:
        form = TournamentForm()

    context = {
        'tournaments': Tournament.objects.all(),
        'form': TournamentForm()
    }
    return render(request, 'management/upcoming_tournament_list.html', context)


@admin_required()
def past_tournament_list_view(request):
    context = {
        'tournaments': Tournament.objects.all()
    }
    return render(request, 'management/past_tournament_list_view.html', context)


@admin_required()
def tournament_detail_view(request, id):
    tournament = Tournament.objects.filter(id=id).first()
    tournament_players = TournamentPlayer.objects.filter(tournament_id=id).select_related('player')
    players = [tp.player for tp in tournament_players]

    class InTournamentResultsForm(forms.Form):
        school1 = forms.ModelChoiceField(
            queryset=SchoolProfile.objects.filter(tournamentregistration__tournament=tournament),
            widget=forms.Select(attrs={'class': 'form-control'})
        )
        school2 = forms.ModelChoiceField(
            queryset=SchoolProfile.objects.filter(tournamentregistration__tournament=tournament),
            widget=forms.Select(attrs={'class': 'form-control'})
        )
        school1_score = forms.IntegerField(
            widget=forms.NumberInput(attrs={'class': 'form-control'})
        )
        school2_score = forms.IntegerField(
            widget=forms.NumberInput(attrs={'class': 'form-control'})
        )
        stage = forms.ChoiceField(
            choices=STAGE_CHOICES,
            widget=forms.Select(attrs={'class': 'form-control'})
        )

    if request.method == "POST":
        form = InTournamentResultsForm(request.POST)
        if form.is_valid():
            result = TournamentResults.objects.create(
                tournament=tournament,
                school1=SchoolProfile.objects.get(id=form.data['school1']),
                school2=SchoolProfile.objects.get(id=form.data['school2']),
                school1_score=form.data['school1_score'],
                school2_score=form.data['school2_score'],
                stage=form.data['stage']
            )
            result.save()
            return redirect('management:admin_tournament_detail', tournament.id)
        else:
            messages.error(request, form.errors)
    else:
        form = InTournamentResultsForm()

    context = {
        'tournament': tournament,
        'form': InTournamentResultsForm(),
        'registered_schools': SchoolProfile.objects.filter(tournamentregistration__tournament=tournament),
        'results': TournamentResults.objects.filter(tournament=tournament),
        'players': players
    }
    return render(request, 'management/tournament_details.html', context)


@admin_required()
def tournament_players_view(request):
    context = {}
    return render(request, 'management/tournament_players.html', context)


@admin_required()
def tournament_registrations_view(request):
    context = {
        'regs': TournamentRegistration.objects.all()
    }
    return render(request, 'management/tournament_registrations.html', context)


@admin_required()
def registration_approval_view(request, id):
    registration = get_object_or_404(TournamentRegistration, id=id)
    registration.approved = True
    registration.save()
    messages.success(request, 'Registration status has been updated.')
    return redirect('management:admin_tournament_registration')


@admin_required()
def schools_view(request):
    context = {
        'schools': SchoolProfile.objects.all()
    }
    return render(request, 'management/schools.html', context)


@admin_required()
def users_view(request):
    context = {}
    return render(request, 'management/users.html', context)


@admin_required()
def results_list_view(request):
    if request.method == "POST":
        form = TournamentResultsForm(request.POST)
        if form.is_valid():
            result = TournamentResults.objects.create(
                tournament=form.data['tournament'],
                school1=form.data['school1'],
                school2=form.data['school2'],
                school1_score=form.data['school1_score'],
                school2_score=form.data['school2_score'],

templates/management/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="favicon.ico">
    <title>PE Football Management</title>
    <!-- Simple bar CSS -->
    <link rel="stylesheet" href="{% static 'css/simplebar.css' %}">
    <!-- Fonts CSS -->
    <link href="https://fonts.googleapis.com/css2?family=Overpass:ital,wght@0,100;0,200;0,300;0,400;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
    <!-- Icons CSS -->
    <link rel="stylesheet" href="{% static 'css/feather.css' %}">
    <link rel="stylesheet" href="{% static 'css/select2.css' %}">
    <link rel="stylesheet" href={% static 'css/dropzone.css' %}"">
    <link rel="stylesheet" href="{% static 'css/uppy.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery.steps.css' %}">
       <link rel="stylesheet" href="{% static 'css/dataTables.bootstrap4.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery.timepicker.css' %}">
    <link rel="stylesheet" href="{% static 'css/quill.snow.css' %}">
    <!-- Date Range Picker CSS -->
    <link rel="stylesheet" href="{% static 'css/daterangepicker.css' %}">
    <!-- App CSS -->
    <link rel="stylesheet" href="{% static 'css/app-light.css' %}" id="lightTheme">


  </head>

<body class="vertical ">


{% block content %}

{% endblock content %}

</body>
</html>

templates/management/gallery_posts.html
{% extends 'management/base.html' %}

{% load static %}
{% block content %}

<div class="wrapper">
 <main role="main" class="main-content">
     {% include 'management/navbar.html' %}

        <div class="container-fluid">
                {% if messages %}
        {% for message in messages %}
            <div class="col-12 mb-4">
              <div class="alert alert-{{ message.tags }} alert-dismissible fade show " style="text-color:blue" role="alert">
                {{ message }}
                 <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                 </button>
                </div>
            </div>
        {% endfor %}
        {% endif %}
          <div class="row justify-content-center">
            <div class="col-12">
              <h2 class="mb-2 page-title">Gallery Posts</h2>
              <p class="card-text">This is a table containing all the videos in the gallery </p>
            <div class="modal fade" id="verticalModal" tabindex="-1" role="dialog" aria-labelledby="verticalModalTitle" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered" role="document">
                          <div class="modal-content">
                            <div class="modal-header">
                              <h5 class="modal-title" id="verticalModalTitle">Add New Video</h5>
                              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                              </button>
                            </div>
                              <form method="post" enctype="multipart/form-data" action="{% url 'management:admin_gallery' %}">
                                  {% csrf_token %}
                        <div class="modal-body">
                                <div class="form-group">
                                  <label for="recipient-name" class="col-form-label">Title:</label>
                                  {{ form.title }}
                                </div>
                            <div class="form-group">
                                  <label for="recipient-name" class="col-form-label">Youtube Url</label>
                                  {{ form.youtube_url }}
                                </div>
                            <div class="form-group">
                                  <label for="recipient-name" class="col-form-label">Description</label>
                                  {{ form.description }}
                                </div>
                            <div class="form-group">
                                  <label for="recipient-name" class="col-form-label">Cover Image</label>
                                  {{ form.cover_image }}
                                </div>

                        </div>
                            <div class="modal-footer">
                              <button type="button" class="btn mb-2 btn-secondary" data-dismiss="modal">Close</button>
                              <button  type="submit" class="btn mb-2 btn-primary">Submit</button>
                            </div>
                              </form>
                          </div>
                        </div>
                      </div>

              <div class="row my-4">
                <!-- Small table -->
                <div class="col-md-12">
                  <div class="card shadow">
                      <div class="card-header">
                       <button class="float-right btn btn-primary" data-toggle="modal" data-target="#verticalModal">Add New Video</button>
                    </div>
                    <div class="card-body">
                      <table class="table datatables" id="dataTable-1">
                        <thead>
                          <tr>
                            <th><strong>#</strong></th>
                              <th><strong>Cover Image</strong></th>
                            <th><strong>Title</strong></th>
                            <th><strong>Youtube Url</strong></th>
                             <th><strong>Date Added</strong></th>
                          </tr>
                        </thead>
                        <tbody id="tbody">
                        {% for content in media_content %}
                          <tr>
                            <td>{{ content.id }}</td>
                              <td><img width="100" height="80" src="{{ content.cover_image.url }}"></td>
                            <td>{{ content.title }}</td>
                            <td>{{ content.youtube_url }}</td>
                            <td>{{ content.date_added }}</td>

                          </tr>
                        {% endfor %}
                        </tbody>
                      </table>
                    </div>
                  </div>
                </div> <!-- simple table -->
              </div> <!-- end section -->
            </div> <!-- .col-12 -->
          </div> <!-- .row -->
        </div> <!-- .container-fluid -->
      </main> <!-- main -->
</div>
<script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/moment.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/simplebar.min.js' %}"></script>
    <script src='{% static 'js/daterangepicker.js' %}'></script>
    <script src='{% static 'js/jquery.stickOnScroll.js' %}'></script>
    <script src="{% static 'js/tinycolor-min.js' %}"></script>
    <script src="{% static 'js/config.js' %}"></script>
    <script src='{% static 'js/jquery.dataTables.min.js' %}'></script>
    <script src='{% static 'js/dataTables.bootstrap4.min.js' %}'></script>
    <script>
      $('#dataTable-1').DataTable(
      {
        autoWidth: true,
        "lengthMenu": [
          [16, 32, 64, -1],
          [16, 32, 64, "All"]
        ]
      });
    </script>
    <script src="{% static 'js/apps.js' %}"></script>
    <!-- Global site tag (gtag.js) - Google Analytics -->

    <script>
      window.dataLayer = window.dataLayer || [];

      function gtag()
      {
        dataLayer.push(arguments);
      }
      gtag('js', new Date());
      gtag('config', 'UA-56159088-1');
    </script>


{% endblock content %}

templates/management/navbar.html
 {% load static %}

      <nav class="topnav navbar navbar-light">

        <button type="button" class="navbar-toggler text-muted mt-2 p-0 mr-3 collapseSidebar">
          <i class="fe fe-menu navbar-toggler-icon"></i>
        </button>

      </nav>
      <aside class="sidebar-left border-right bg-white shadow" id="leftSidebar" data-simplebar>
        <a href="#" class="btn collapseSidebar toggle-btn d-lg-none text-muted ml-2 mt-3" data-toggle="toggle">
          <i class="fe fe-x"><span class="sr-only"></span></i>
        </a>
        <nav class="vertnav navbar navbar-light">
          <!-- nav bar -->
{#          <div class="w-100 mb-4 d-flex">#}
{#            <a class="navbar-brand mx-auto mt-2 flex-fill text-center" href="{% url 'management:admin_dashboard' %}">#}
{#              <img src="{% static 'assets/images/logo.png' %}">#}
{#            </a>#}
{#          </div>#}
          <ul class="navbar-nav flex-fill w-100 mb-4">
            <li class="nav-item mb-4">
            </li>
          </ul>

          <ul class="navbar-nav flex-fill w-100 mb-2">
            <li class="nav-item w-100">
              <a class="nav-link" href="{% url 'management:admin_upcoming_tournaments-list' %}">
                <i class="fe fe-monitor fe-16"></i>
                <span class="ml-3 item-text">Tournaments</span>
              </a>
            </li>
{#            <li class="nav-item w-100">#}
{#              <a class="nav-link" href="{% url 'management:admin_past_tournaments-list' %}">#}
{#                <i class="fe fe-tv fe-16"></i>#}
{#                <span class="ml-3 item-text">Past Tournaments</span>#}
{#              </a>#}
{#            </li>#}
             <li class="nav-item w-100">
              <a class="nav-link" href="{% url 'management:admin_tournament_registration' %}">
                <i class="fe fe-download fe-16"></i>
                <span class="ml-3 item-text">Tournament Registrations</span>
              </a>
            </li>

              <li class="nav-item w-100">
              <a class="nav-link" href="{% url 'management:admin_result_list' %}">
                <i class="fe fe-clipboard fe-16"></i>
                <span class="ml-3 item-text">Results List</span>
              </a>
            </li>

            <li class="nav-item w-100">
              <a class="nav-link" href="{% url 'management:admin_gallery' %}">
                <i class="fe fe-camera fe-16"></i>
                <span class="ml-3 item-text">Gallery Posts</span>
              </a>
            </li>

             <li class="nav-item w-100">
              <a class="nav-link" href="{% url 'management:admin_schools' %}">
                <i class="fe fe-book-open fe-16"></i>
                <span class="ml-3 item-text">Schools</span>
              </a>
            </li>

              <li class="nav-item w-100">
              <a class="nav-link" href="{% url 'management:admin_player_list' %}">
                <i class="fe fe-users fe-16"></i>
                <span class="ml-3 item-text">All Players</span>
              </a>
            </li>
{##}
{#          <li class="nav-item w-100">#}
{#              <a class="nav-link" href="{% url 'management:admin_users' %}">#}
{#                <i class="fe fe-log-out fe-16"></i>#}
{#                <span class="ml-3 item-text">Users</span>#}
{#              </a>#}
{#            </li>#}

            <li class="nav-item w-100">
              <a class="nav-link" href="{% url 'management:admin_logout' %}">
                <i class="fe fe-log-out fe-16"></i>
                <span class="ml-3 item-text">Log Out</span>
              </a>
            </li>


          </ul>
        </nav>
      </aside>

templates/management/past_tournament_detail_view.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/management/user_login.html
{% extends 'management/base.html' %}
{% load static %}
{% load crispy_forms_tags %}


{% block content %}

<div class="wrapper vh-100">
      <div class="row align-items-center h-100">
        <form class="col-lg-3 col-md-4 col-10 mx-auto text-center" method="POST">
            {% csrf_token %}

{#            <img height="60px" src="{% static 'assets/images/zrplogo1.jpeg' %}">#}
          <h1 class="mt-3 mb-3 title"><strong>Admin Portal Login</strong></h1>

            {{ form | crispy }}

{#          <div class="form-group">#}
{#            <label for="inputEmail" class="sr-only">Email address</label>#}
{#            <input type="email" id="inputEmail" class="form-control form-control-lg" placeholder="Email address" required="" autofocus="">#}
{#          </div>#}
{#          <div class="form-group">#}
{#            <label for="inputPassword" class="sr-only">Password</label>#}
{#            <input type="password" id="inputPassword" class="form-control form-control-lg" placeholder="Password" required="">#}
{#          </div>#}
          <button class="btn btn-lg btn-primary btn-block" type="submit">Log In</button>
            <a href="{% url 'core:home' %}"><button class="btn btn-lg btn-dark btn-block mt-3" type="button">Return To Main Site</button></a>
          <p class="mt-5 mb-3 text-muted">© 2024</p>
        </form>
      </div>
    </div>


{% endblock content %}

templates/management/users.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>