core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.home_view, name='home'),
    path('gallery/', views.gallery_view, name='gallery'),
    path('results/', views.result_view, name='result'),
    path('tournaments/', views.tournament_view, name='tournaments'),
    # path('tournaments/', views.tournaments_list, name='tournaments_list'),
    # path('tournaments/<int:tournament_id>/', views.tournament_detail, name='tournament_detail'),
]

pe_football/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include
from django.conf.urls.static import static

from pe_football import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('schools/', include('schools.urls', namespace='schools')),
    path('management/', include('management.urls', namespace='management')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

schools/urls.py
from django.urls import path
from . import views

app_name = 'schools'

urlpatterns = [
    path('register/', views.UserRegistrationView.as_view(), name='school_register'),
    path('login/', views.UserLoginView.as_view(), name='school_login'),
    path('logout/', views.user_logout_view, name='school_logout'),
    path('dashboard/', views.dashboard_view, name='school_dashboard'),
    path('upcoming-tournaments/', views.upcoming_tournaments_view, name='upcoming_tournaments'),
    path('registerd-tournaments/', views.registered_tournaments_view, name='registered_tournaments'),
    path('register-tournament/<int:id>/', views.register_tournament_view, name='register_tournament'),
    path('tournament-detail/<int:id>/', views.tournament_detail_view, name='tournament_detail'),
    path('tournament/<int:tournament_id>/register-players/', views.register_players_for_tournament_view, name='register_players_for_tournament'),
    path('player-list/', views.players_list_view, name='player_list'),
    path('players/create/', views.create_player_view, name='create_player'),
    path('player-profile/<int:id>/', views.player_profile_view, name='player_profile'),
    path('result-list/', views.results_list_view, name='result_list'),
    path('create-school-profile/', views.create_school_profile_view, name='create_school_profile'),
    # path('tournaments/<int:tournament_id>/players/', views.select_players, name='select_players'),
]

core/models.py
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import AbstractUser, PermissionsMixin
from django.db import models


# Create your models here.
class MyUserManager(BaseUserManager):
    def create_user(self, email, first_name, last_name, password=None):
        """
        Creates and saves a User with the given email, date of
        birth and password.
        """
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=self.normalize_email(email),
            first_name=first_name,
            last_name=last_name,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, first_name, last_name, password):
        """
        Creates and saves a superuser with the given email, date of
        birth and password.
        """
        user = self.create_user(
            email,
            password=password,
            first_name=first_name,
            last_name=last_name,
        )
        user.is_admin = True
        user.is_staff = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser):
    email = models.EmailField(
        verbose_name='email address',
        max_length=255,
        unique=True,
    )
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255, blank=True)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    is_school = models.BooleanField(default=False)

    objects = MyUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name']

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def full_name(self):
        return self.first_name + ' ' + self.last_name

    def __str__(self):
        return self.full_name

core/views.py
from django.shortcuts import render
from management.models import Tournament, TournamentResults, MediaContent
from schools.models import SchoolProfile, Player
# Create your views here.


def home_view(request):
    ctx = {
        'tournament': Tournament.objects.last(),
        'result': TournamentResults.objects.last(),
        'total_games': TournamentResults.objects.all().count(),
        'total_players': Player.objects.all().count(),
        'total_tournaments': Tournament.objects.all().count(),
        'total_schools': SchoolProfile.objects.all().count()
    }
    return render(request, 'core/index.html', ctx)


def gallery_view(request):
    ctx = {
        'media_content': MediaContent.objects.all()
    }
    return render(request, 'core/gallery.html', ctx)



def result_view(request):
    ctx = {
        'results': TournamentResults.objects.all()
    }
    return render(request, 'core/results.html', ctx)



def tournament_view(request):
    ctx = {
        'tournaments': Tournament.objects.all()
    }
    return render(request, 'core/tournaments.html', ctx)

templates/core/base.html
{% load static %}

<!doctype html>
<!--[if lt IE 7]>		<html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="zxx"> <![endif]-->
<!--[if IE 7]>			<html class="no-js lt-ie9 lt-ie8" lang="zxx"> <![endif]-->
<!--[if IE 8]>			<html class="no-js lt-ie9" lang="zxx"> <![endif]-->
<!--[if gt IE 8]><!-->	<html class="no-js" lang="zxx"> <!--<![endif]-->


<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>Prince Edward Football</title>
	<meta name="description" content="">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="apple-touch-icon" href="apple-touch-icon.png">
	<link rel="stylesheet" href="{% static 'core/css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static 'core/css/normalize.css' %}">
	<link rel="stylesheet" href="{% static 'core/css/font-awesome.min.css' %}">
	<link rel="stylesheet" href="{% static 'core/css/transitions.css' %}">
	<link rel="stylesheet" href="{% static 'core/css/prettyPhoto.css' %}">
	<link rel="stylesheet" href="{% static 'core/css/swiper.min.css' %}">
	<link rel="stylesheet" href="{% static 'core/css/jquery-ui.css' %}">
	<link rel="stylesheet" href="{% static 'core/css/animate.css' %}">
	<link rel="stylesheet" href="{% static 'core/css/owl.theme.css' %}">
	<link rel="stylesheet" href="{% static 'core/css/owl.carousel.css' %}">
	<link rel="stylesheet" href="{% static 'core/css/customScrollbar.css' %}">
	<link rel="stylesheet" href="{% static 'core/css/icomoon.css' %}">
	<link rel="stylesheet" href="{% static 'core/css/main.css' %}">
	<link rel="stylesheet" href="{% static 'core/css/color.css' %}">
	<link rel="stylesheet" href="{% static 'core/css/responsive.css' %}">
	<script src="{% static 'core/js/vendor/modernizr-2.8.3-respond-1.4.2.min.js' %}"></script>
</head>
<body>

{% block content %}


{% endblock content %}

	<script src="{% static 'core/js/vendor/jquery-library.js' %}"></script>
	<script src="{% static 'core/js/vendor/bootstrap.min.js' %}"></script>
	<script src="{% static 'core/js/customScrollbar.min.js' %}"></script>
	<script src="{% static 'core/js/owl.carousel.js' %}"></script>
	<script src="{% static 'core/js/isotope.pkgd.js' %}"></script>
	<script src="{% static 'core/js/prettyPhoto.js' %}"></script>
	<script src="{% static 'core/js/swiper.min.js' %}"></script>
	<script src="{% static 'core/js/jquery-ui.js' %}"></script>
	<script src="{% static 'core/js/countTo.js' %}"></script>
	<script src="{% static 'core/js/appear.js' %}"></script>
	<script src="{% static 'core/js/main.js' %}"></script>
</body>


</html>

templates/core/footer.html
		<footer id="tg-footer" class="tg-footer tg-haslayout">
			<div class="tg-footerbar">
				<div class="container">
					<span class="tg-copyright"><a target="_blank" href="https://www.linkedin.com/in/gift-mugaragumbo-91bb46202frf0/">Gift Mugaragumbo</a></span>
					<nav class="tg-footernav">
						<ul>
							<li><a href="{% url 'core:home' %}">Home</a></li>
							<li><a href="{% url 'core:tournaments' %}">Tournaments</a></li>
							<li><a href="{% url 'core:result' %}">Results</a></li>
							<li><a href="{% url 'core:gallery' %}">Gallery</a></li>
							<li><a href="https://peschool.co.zw/">Contact</a></li>
						</ul>
					</nav>
				</div>
			</div>
		</footer>

templates/core/gallery.html
{% extends 'core/base.html' %}
{% load static %}


{% block content %}

	<!--************************************
			Wrapper Start
	*************************************-->
	<div id="tg-wrapper" class="tg-wrapper tg-haslayout">
		<!--************************************
				Mobile Menu Start
		*************************************-->
{% include 'core/mobile_menu.html' %}
		<!--************************************
				Mobile Menu End
		*************************************-->
		<!--************************************
				Header Start
		*************************************-->
		<header id="tg-header" class="tg-header tg-haslayout">
			{% include 'core/navbar.html' %}
		</header>
		<!--************************************
				Header End
		*************************************-->
		<!--************************************
				Banner Start
		*************************************-->
		<div class="tg-banner tg-haslayout">
			<div class="tg-imglayer">
				<img src="{% static 'core/images/bg-pattran.png' %}" alt="image desctription">
			</div>
			<div class="container">
				<div class="row">
					<div class="tg-banner-content tg-haslayout">
						<div class="tg-pagetitle">
							<h1 style="color:white;">PE Soccer Media</h1>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!--************************************
				Banner End
		*************************************-->
		<!--************************************
				Main Start
		*************************************-->
		<main id="tg-main" class="tg-main tg-haslayout">
			<!--************************************
					Soccer Media Start
			*************************************-->
			<section class="tg-main-section tg-soccermedia tg-haslayout">
				<div class="container">
					<div class="col-sm-12 col-xs-12 pull-right">
						<div class="row">
							<div class="tg-tg-soccermedia-head tg-haslayout">
								<ul id="tg-filterbale-nav" class="tg-filterbale-nav option-set">
{#									<li><a class="active" data-filter="*" href="javascript:void(0);">All</a></li>#}
{#									<li><a data-filter=".laliga" href="javascript:void(0);">La Liga</a></li>#}
{#									<li><a data-filter=".championship" href="javascript:void(0);">Championship</a></li>#}
{#									<li><a data-filter=".scottishpremiership" href="javascript:void(0);">scottish Premiership</a></li>#}
{#									<li><a data-filter=".bundesliga" href="javascript:void(0);">Bundesliga</a></li>#}
								</ul>
							</div>
							<div id="filter-masonry" class="tg-soccermedia-content tg-soccermedia-content2 tg-haslayout">
                                {% for content in media_content %}
								<div class="masonry-grid laliga">
									<div class="tg-project">
										<figure class="tg-postimg">
											<img src="{{ content.cover_image.url }}" alt="image description">
											<figcaption>
												<a class="tg-theme-tag" data-rel="prettyPhoto[iframe]" href="{{ content.youtube_url }}"><i class="fa fa-play"></i></a>
												<a class="tg-theme-tag">{{ content.date_added }}</a>
												<h3>{{ content.title }}</h3>
											</figcaption>
										</figure>
									</div>
								</div>
                                {% endfor %}
							</div>
						</div>
					</div>
				</div>
			</section>
			<!--************************************
					Soccer Media End
			*************************************-->
		</main>
		<!--************************************
				Main End
		*************************************-->
		<!--************************************
				Footer Start
		*************************************-->
		{% include 'core/footer.html' %}
		<!--************************************
				Footer End
		*************************************-->
	</div>
	<!--************************************
			Wrapper End
	*************************************-->




{% endblock content %}

templates/core/index.html
{% extends 'core/base.html' %}
{% load static %}


{% block content %}


	<!--************************************
			Wrapper Start
	*************************************-->
	<div id="tg-wrapper" class="tg-wrapper tg-haslayout">
		<!--************************************
				Mobile Menu Start
		*************************************-->
		{% include 'core/mobile_menu.html' %}
		<!--************************************
				Mobile Menu End
		*************************************-->
		<!--************************************
				Header Start
		*************************************-->
		<header id="tg-header" class="tg-header tg-haslayout">
        {% include 'core/navbar.html' %}
		</header>
		<!--************************************
				Header End
		*************************************-->
		<!--************************************
				Home Slider Start
		*************************************-->
		<div class="tg-sliderbox">
			<div class="tg-imglayer">
				<img src="{% static 'core/images/bg-pattran.png' %}" alt="image desctription">
			</div>
			<div id="tg-home-slider" class="tg-home-slider tg-haslayout">
				<div class="swiper-wrapper">
					<div class="swiper-slide">
						<div class="container">
							<figure class="floating">
								<img src="{% static 'core/images/slider/img-01.png' %}" alt="image description">
							</figure>
							<div class="tg-slider-content">
								<h1>Prince Edward</h1>
								<div class="tg-btnbox">
									<a class="tg-btn" href="{% url 'schools:school_register' %}"><span>Register School</span></a>
									<a class="tg-btn" href="{% url 'schools:school_login' %}"><span>School Login</span></a>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!--************************************
				Home Slider End
		*************************************-->
		<!--************************************
				Main Start
		*************************************-->
		<main id="tg-main" class="tg-main tg-haslayout">
			<!--************************************
					About Us Start
			*************************************-->
			<section class="tg-main-section tg-haslayout">
				<div class="container">
					<div class="tg-section-name">
						<h2>Upcoming Tournament</h2>
					</div>
					<div class="col-sm-11 col-xs-11 pull-right">
						<div class="row">
							<div class="tg-aboutussection">
								<div class="row">
									<div class="col-md-6 col-sm-12 col-xs-12">
										<figure>
											<img src="{% static 'core/images/img-01.jpg' %}" alt="image description">
										</figure>
									</div>
									<div class="col-md-6 col-sm-12 col-xs-12">
										<div class="tg-contentbox">
											<div class="tg-section-heading"><h2>{{ tournament.name }}</h2></div>
											<div class="tg-description">
												<p>The tournament will be held at{{ tournament.venue }} on {{  tournament.start_date }}. The games will begin at {{ tournament.time }}. The age limit for the tournament is {{ tournament.age_limit }}. A participation fee of  ${{ tournament.participation_fee }} is required to register for the tournament</p>
											</div>
											<div class="tg-btnbox">
												<a class="tg-btn" href="{% url 'schools:tournament_detail' tournament.id %}"><span>Register for Tournament</span></a>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</section>
			<!--************************************
					About Us End
			*************************************-->
			<section class="tg-main-section tg-haslayout">
				<div class="container">
					<div class="tg-section-name">
						<h2>latest result</h2>
					</div>
					<div class="col-sm-11 col-xs-11 pull-right">
						<div class="row">
							<div class="tg-latestresult">
								<div class="row">
									<div class="col-md-12 col-sm-12 col-xs-12">
										<div class="tab-content tg-tabscontent">
											<div role="tabpanel" class="tab-pane active" id="one">
												<div class="tg-matchresult">
													<div class="tg-box">
														<div class="tg-score"><h3>{{ result.school1_score }} - {{ result.school2_score }}</h3></div>
														<div class="tg-teamscore">
															<strong class="tg-team-logo">
																<a href="#">
																	<img src="{{ result.school2.logo.url }}" alt="image description">
																</a>
															</strong>
															<div class="tg-team-nameplusstatus">
																<h4 style="color: white">{{ result.school1.name }}</h4>
															</div>
														</div>
														<div class="tg-teamscore">
															<strong class="tg-team-logo">
																<a href="#">
																	<img src="{{ result.school1.logo.url }}" alt="image description">
																</a>
															</strong>
															<div class="tg-team-nameplusstatus">
																<h4>{{ result.school2.name }}</h4>
															</div>
														</div>
													</div>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</section>
			<!--************************************
					Latest Result End
			*************************************-->
			<!--************************************
					Statistics Start
			*************************************-->
			<section class="tg-main-section tg-haslayout tg-bgdark" style="margin-bottom: 20px">
				<div class="container">
					<div class="row">
						<div class="col-sm-12 col-xs-12">
							<div class="tg-statistics">
                                <div class="tg-statistic tg-activeteams">
									<span class="tg-icon icon-Icon2"></span>
									<h2><span class="tg-statistic-count" data-from="0" data-to="236" data-speed="8000" data-refresh-interval="50">{{ total_schools }}</span></h2>
									<h3>Registered Schools</h3>
								</div>
								<div class="tg-statistic tg-activeplayers">
									<span class="tg-icon icon-Icon3"></span>
									<h2><span class="tg-statistic-count" data-from="0" data-to="1673" data-speed="8000" data-refresh-interval="50">{{ total_players }}</span></h2>
									<h3>Registered Players</h3>
								</div>
								<div class="tg-statistic tg-earnedawards">
									<span class="tg-icon icon-Icon4"></span>
									<h2><span class="tg-statistic-count" data-from="0" data-to="197" data-speed="8000" data-refresh-interval="50">{{ total_tournaments }}</span></h2>
									<h3>Tournaments</h3>
								</div>
                                <div class="tg-statistic tg-goals">
									<span class="tg-icon icon-Icon1"></span>
									<h2><span class="tg-statistic-count" data-from="0" data-to="2700" data-speed="8000" data-refresh-interval="50">{{ total_games }}</span></h2>
									<h3>Games Played</h3>
								</div>
							</div>
						</div>
					</div>
				</div>
			</section>
			<!--************************************
					Statistics End
			*************************************-->
			<!--************************************
					Video Start
			*************************************-->
			<section class="tg-videobox tg-haslayout">
				<figure>
					<img src="{% static 'core/images/bg-video.jpg' %}" alt="image description">
					<figcaption>
						<a class="tg-playbtn" href="https://youtu.be/iC9CpnSj-MU?iframe=true" data-rel="prettyPhoto[iframe]"></a>
						<h2>Previous game highlights</h2>
					</figcaption>
				</figure>
			</section>
			<!--************************************
					Video End
			*************************************-->
		</main>
		<!--************************************
				Main End
		*************************************-->
		<!--************************************
				Footer Start
		*************************************-->
{% include 'core/footer.html' %}
		<!--************************************
				Footer End
		*************************************-->
	</div>
	<!--************************************
			Wrapper End



{% endblock content %}

templates/core/mobile_menu.html
		<div id="tg-navigationm-mobile" class="tg-navigationm-mobile tg-navigation collapse navbar-collapse">
			<span id="tg-close" class="tg-close fa fa-close"></span>
			<div class="tg-colhalf">
                <ul>
                    <li>
                        <a href="#">Main</a>
                        <ul class="tg-dropdown-menu">
                            <li><a href="index-2.html">home1</a></li>
                            <li><a href="index2.html">home2</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="#">team</a>
                        <ul class="tg-dropdown-menu">
                            <li><a href="playergrid-v1.html">playergrid-v1</a></li>
                            <li><a href="playergrid-v2.html">playergrid-v2</a></li>
                            <li><a href="playerdetail.html">playergrid detail</a></li>
                        </ul>
                    </li>
                    <li><a href="buyticket.html">Buy Tickets</a></li>
                    <li>
                        <a href="#">Match Results</a>
                        <ul class="tg-dropdown-menu">
                            <li><a href="matchresult.html">match result</a></li>
                            <li><a href="matchresultdetail.html">match result detail</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
            <div class="tg-colhalf">
                <ul>
                    <li>
                        <a href="#">fixtures</a>
                        <ul class="tg-dropdown-menu">
                            <li><a href="fixtures.html">fixtures</a></li>
                            <li><a href="fixturedetail.html">fixture detail</a></li>
                        </ul>
                    </li>
                    <li class="active">
                        <a href="#">pro soccer media</a>
                        <ul class="tg-dropdown-menu">
                            <li><a href="soccermedia-1.html">pro soccer media1</a></li>
                            <li class="active"><a href="soccermedia-2.html">pro soccer media2</a></li>
                        </ul>
                    </li>
                    <li><a href="contactus.html">Contact</a></li>
                    <li>
                        <a href="#"><i class=" fa fa-navicon"></i></a>
                        <ul>
                            <li><a href="aboutus.html">about us</a></li>
                            <li><a href="shoplist.html">shop list</a></li>
                            <li><a href="shopgrid.html">shop grid</a></li>
                            <li><a href="productsingle.html">shop detail</a></li>
                            <li><a href="bloglist.html">blog list</a></li>
                            <li><a href="bloggrid.html">blog grid</a></li>
                            <li><a href="blogdetail.html">blog detail</a></li>
                            <li><a href="404.html">404 error</a></li>
                            <li><a href="comming-soon.html">comming soon</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
		</div>

templates/core/navbar.html
{% load static %}

<div class="container">
				<div class="col-md-10 col-md-offset-1 col-sm-12 col-xs-12">
					<div class="row">
						<div class="tg-topbar tg-haslayout">
							<nav id="tg-topaddnav" class="tg-topaddnav">
								<div class="navbar-header">
									<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#tg-addnavigationm-mobile">
										<i class="fa fa-arrow-right"></i>
									</button>
								</div>
								<div id="tg-addnavigationm-mobile" class="tg-addnavigationm-mobile collapse navbar-collapse">
									<div class="tg-colhalf pull-right">
										<nav class="tg-addnav">
											<ul>

                                                <li><a href="{% url 'core:gallery' %}">Gallery</a></li>
                                                <li><a href="https://peschool.co.zw/">Contact</a></li>
											</ul>
										</nav>
									</div>
									<div class="tg-colhalf" >
										<nav class="tg-addnav ">
											<ul >
                                                <li class="active"><a href="{%  url 'core:home' %}">           Home</a></li>
                                                <li><a href="{% url 'core:tournaments' %}">Tournaments</a></li>
                                                <li><a href="{% url 'core:result' %}">Results</a></li>

											</ul>
										</nav>
									</div>
								</div>
							</nav>
						</div>
						<nav id="tg-nav" class="tg-nav brand-center">
							<div class="navbar-header">
								<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#tg-navigationm-mobile">
									<i class="fa fa-bars"></i>
								</button>
								<strong class="tg-logo">
									<a href="{% url 'core:home' %}"><img src="{% static 'pe logo.jpeg' %}" alt="image description"></a>
								</strong>
							</div>
						</nav>
					</div>
				</div>
			</div>

templates/core/tournaments.html
{% extends 'core/base.html' %}
{% load static %}


{% block content %}

<body>
	<!--[if lt IE 8]>
		<p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
	<![endif]-->
	<!--************************************
			Wrapper Start
	*************************************-->
	<div id="tg-wrapper" class="tg-wrapper tg-haslayout">
		<!--************************************
				Mobile Menu Start
		*************************************-->
		{% include 'core/mobile_menu.html' %}
		<!--************************************
				Mobile Menu End
		*************************************-->
		<!--************************************
				Header Start
		*************************************-->
		<header id="tg-header" class="tg-header tg-haslayout">
			{% include 'core/navbar.html' %}
		</header>
		<!--************************************
				Header End
		*************************************-->
		<!--************************************
				Banner Start
		*************************************-->
		<div class="tg-banner tg-haslayout">
			<div class="tg-imglayer">
				<img src="{% static 'core/images/bg-pattran.png' %}" alt="image desctription">
			</div>
			<div class="container">
				<div class="row">
					<div class="tg-banner-content tg-haslayout">
						<div class="tg-pagetitle">
							<h1 style="color:white;">Upcoming Tournaments</h1>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!--************************************
				Banner End
		*************************************-->
		<!--************************************
				Main Start
		*************************************-->
		<main id="tg-main" class="tg-main tg-haslayout">
		<section class="tg-main-section tg-haslayout">
				<div class="container">
					<div class="tg-section-name">
						<h2>Upcoming Tournament</h2>
					</div>
					<div class="col-sm-11 col-xs-11 pull-right">
						<div class="row">
                            {% for tournament in tournaments %}
							<div class="tg-aboutussection" style="margin-bottom: 60px">
								<div class="row">
									<div class="col-md-6 col-sm-12 col-xs-12">
										<figure>
											<img src="{% static 'core/images/img-01.jpg' %}" alt="image description">
										</figure>
									</div>
									<div class="col-md-6 col-sm-12 col-xs-12">
										<div class="tg-contentbox">
											<div class="tg-section-heading"><h2>{{ tournament.name }}</h2></div>
											<div class="tg-description">
												<p>The tournament will be held at{{ tournament.venue }} on {{  tournament.start_date }}. The games will begin at {{ tournament.time }}. The age limit for the tournament is {{ tournament.age_limit }}. A participation fee of  ${{ tournament.participation_fee }} is required to register for the tournament</p>
											</div>
											<div class="tg-btnbox">
												<a class="tg-btn" href="{% url 'schools:tournament_detail' tournament.id %}"><span>Register for Tournament</span></a>
											</div>
										</div>
									</div>
								</div>
							</div>
                            {% endfor %}
						</div>
					</div>
				</div>
			</section>
		</main>
		<!--************************************
				Main End
		*************************************-->
		<!--************************************
				Footer Start
		*************************************-->
		{% include 'core/footer.html' %}
		<!--************************************
				Footer End
		*************************************-->
	</div>
	<!--************************************
			Wrapper End
	*************************************-->



{% endblock content %}