core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.home_view, name='home'),
    path('gallery/', views.gallery_view, name='gallery'),
    path('results/', views.result_view, name='result'),
    path('tournaments/', views.tournament_view, name='tournaments'),
    # path('tournaments/', views.tournaments_list, name='tournaments_list'),
    # path('tournaments/<int:tournament_id>/', views.tournament_detail, name='tournament_detail'),
]

management/urls.py
from django.urls import path
from . import views

app_name = 'management'

urlpatterns = [
    path('login/', views.UserLoginView.as_view(), name='admin_login'),
    path('dashboard/', views.dashboard_view, name='admin_dashboard'),
    path('past-tournaments-list/', views.past_tournament_list_view, name='admin_past_tournaments-list'),
    path('upcoming-tournaments-list/', views.upcoming_tournament_list_view, name='admin_upcoming_tournaments-list'),
    path('tournament-detail/<int:id>/', views.tournament_detail_view, name="admin_tournament_detail"),
    path('tournament-registrations/', views.tournament_registrations_view, name="admin_tournament_registration"),
    path('tournament-approval/<int:id>/', views.registration_approval_view, name="admin_tournament_approval"),
    path('tournament-players/', views.tournament_players_view, name="admin_tournament_players"),
    path('generate-id/<int:player_id>/', views.generate_id_card, name='generate_id_card'),
    path('results-list/', views.results_list_view, name="admin_result_list"),
    path('schools/', views.schools_view, name="admin_schools"),
    path('gallery-posts/', views.gallery_posts_view, name="admin_gallery"),
    path('players/', views.player_list_view, name="admin_player_list"),
    path('player-profile/<int:id>/', views.player_profile_view, name="admin_player_profile"),
    path('logout/', views.logout_view, name="admin_logout"),
    path('users/', views.users_view, name="admin_users"),
    # path('tournaments/<int:tournament_id>/approve/', views.approve_tournament_registration, name='approve_tournament_registration'),
    # path('tournaments/<int:tournament_id>/players/', views.view_tournament_players, name='view_tournament_players'),
    # path('tournaments/<int:tournament_id>/results/', views.upload_tournament_results, name='upload_tournament_results'),
]

pe_football/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include
from django.conf.urls.static import static

from pe_football import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('schools/', include('schools.urls', namespace='schools')),
    path('management/', include('management.urls', namespace='management')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

schools/urls.py
from django.urls import path
from . import views

app_name = 'schools'

urlpatterns = [
    path('register/', views.UserRegistrationView.as_view(), name='school_register'),
    path('login/', views.UserLoginView.as_view(), name='school_login'),
    path('logout/', views.user_logout_view, name='school_logout'),
    path('dashboard/', views.dashboard_view, name='school_dashboard'),
    path('upcoming-tournaments/', views.upcoming_tournaments_view, name='upcoming_tournaments'),
    path('registerd-tournaments/', views.registered_tournaments_view, name='registered_tournaments'),
    path('register-tournament/<int:id>/', views.register_tournament_view, name='register_tournament'),
    path('tournament-detail/<int:id>/', views.tournament_detail_view, name='tournament_detail'),
    path('tournament/<int:tournament_id>/register-players/', views.register_players_for_tournament_view, name='register_players_for_tournament'),
    path('player-list/', views.players_list_view, name='player_list'),
    path('players/create/', views.create_player_view, name='create_player'),
    path('player-profile/<int:id>/', views.player_profile_view, name='player_profile'),
    path('result-list/', views.results_list_view, name='result_list'),
    path('create-school-profile/', views.create_school_profile_view, name='create_school_profile'),
    # path('tournaments/<int:tournament_id>/players/', views.select_players, name='select_players'),
]

schools/models.py
from datetime import datetime
from core.models import User
from django.db import models


# Create your models here.


class SchoolProfile(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    email = models.EmailField()
    phone = models.CharField(max_length=50)
    city = models.CharField(max_length=50)
    province = models.CharField(max_length=50)
    logo = models.ImageField(upload_to='school logos/')
    date_registered = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Player(models.Model):
    school = models.ForeignKey(SchoolProfile, on_delete=models.CASCADE)
    passport_photo = models.ImageField(upload_to='players/')
    national_id = models.CharField(max_length=50, unique=True)
    national_id_image = models.FileField(upload_to='national ids/')
    birth_certificate = models.FileField(upload_to='certificates/')
    grade_7_result = models.FileField(upload_to='results/')
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    middle_name = models.CharField(max_length=255, default='')
    birth_certificate_number = models.CharField(max_length=255)
    guardian_name = models.CharField(max_length=255)
    guardian_relationship = models.CharField(max_length=255)
    guardian_contact = models.CharField(max_length=255)
    date_of_birth = models.DateField()
    present_school = models.CharField(max_length=255)
    year_enrolled = models.CharField(max_length=255)
    previous_school = models.CharField(max_length=255)
    cell = models.CharField(max_length=255)
    position = models.CharField(max_length=255)
    approved = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


    def __str__(self):
        return f"{self.first_name} {self.middle_name} {self.last_name}   |  Age: {self.age} |  Position: {self.position}".strip()

    @property
    def age(self):
        return datetime.today().year - self.date_of_birth.year


class TournamentRegistration(models.Model):
    school = models.ForeignKey(SchoolProfile, on_delete=models.CASCADE)
    tournament = models.ForeignKey('management.Tournament', on_delete=models.CASCADE)
    proof_of_payment = models.FileField(upload_to='proofs of payment/')
    approved = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.school.name} - {self.tournament.name}"

    def approve_reg(self):
        self.approved = True


class TournamentPlayer(models.Model):
    tournament = models.ForeignKey('management.Tournament', on_delete=models.CASCADE)
    player = models.ForeignKey(Player, on_delete=models.CASCADE)
    approved = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = ('tournament', 'player')

    def __str__(self):
        return f"{self.player.name} - {self.tournament.name}"

schools/views.py
from django.contrib import messages
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.core.mail import EmailMessage
from django import forms
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views.decorators.cache import cache_control
from core.admin import UserCreationForm
from core.models import User
from django.contrib.auth.forms import AuthenticationForm
from django.views.generic import CreateView
from django.contrib.auth.views import LoginView
from .models import SchoolProfile, TournamentRegistration, Player, TournamentPlayer
from .forms import SchoolProfileForm, PlayerForm, TournamentPlayerForm, TournamentRegistrationForm, RegisterPlayersForm
from management.models import Tournament, TournamentResults
from .decorators import school_required


# Create your views here.

class UserRegistrationView(CreateView):
    model = User
    form_class = UserCreationForm
    template_name = 'schools/register_user.html'
    success_url = reverse_lazy('schools:create_school_profile')

    def form_valid(self, form):
        response = super().form_valid(form)
        email = form.cleaned_data.get('email')
        password = form.cleaned_data.get('password1')
        user = User.objects.get(email=email)
        login(self.request, user)
        return redirect('schools:create_school_profile')


class UserLoginView(LoginView):
    template_name = 'schools/user_login.html'

    def get_success_url(self):
        if SchoolProfile.objects.filter(user=self.request.user).exists():
            return reverse_lazy('schools:school_dashboard')
        else:
            return reverse_lazy('schools:create_school_profile')


@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def user_logout_view(request):
    logout(request)
    return redirect('schools:school_login')


@school_required()
def dashboard_view(request):
    profile = SchoolProfile.objects.filter(user=request.user).first()
    name = profile.name
    logo = profile.logo
    total_result = TournamentResults.objects.filter(school1=profile).count() + TournamentResults.objects.filter(school2=profile).count()
    total_players = Player.objects.filter(school=profile).count()
    total_defenders = Player.objects.filter(position='Defender').count()
    total_goalkeeper = Player.objects.filter(position='Goalkeeper').count()
    total_attack = Player.objects.filter(position='Forward').count()
    total_midfielder = Player.objects.filter(position='Midfielder').count()
    context = {
        'name': name,
        'logo': logo.url,
        'total_players':total_players,
        'total_results': total_result,
        'total_midfielder':total_midfielder,
        'total_attack': total_attack,
        'total_goalkeeper': total_goalkeeper,
        'total_defender': total_defenders,
        'tournaments': Tournament.objects.all()
    }
    return render(request, 'schools/index.html', context)


@school_required()
def upcoming_tournaments_view(request):
    profile = SchoolProfile.objects.filter(user=request.user).first()
    name = profile.name
    logo = profile.logo
    registered_tournaments = TournamentRegistration.objects.filter(school=profile).values_list('tournament', flat=True)
    unregistered_tournaments = Tournament.objects.exclude(id__in=registered_tournaments)
    context = {
        'tournaments': unregistered_tournaments,
        'name': name,
        'logo': logo.url,
    }
    return render(request, 'schools/upcoming_tournaments.html', context)


@school_required()
def registered_tournaments_view(request):
    profile = SchoolProfile.objects.filter(user=request.user).first()
    name = profile.name
    logo = profile.logo

    context = {
        'name': name,
        'logo': logo.url,
        'tournaments': Tournament.objects.filter(tournamentregistration__school=profile)
    }
    return render(request, 'schools/registered_tournaments.html', context)


@school_required()
def results_list_view(request):
    profile = SchoolProfile.objects.filter(user=request.user).first()
    name = profile.name
    logo = profile.logo
    context = {
        'name': name,
        'logo': logo.url,
        'tournament_results': TournamentResults.objects.filter(school1=profile) | TournamentResults.objects.filter(school2=profile)
    }
    return render(request, 'schools/result_list.html', context)


@school_required()
def players_list_view(request):
    profile = SchoolProfile.objects.filter(user=request.user).first()
    name = profile.name
    logo = profile.logo
    players = Player.objects.filter(school=profile)
    context = {
        'name': name,
        'logo': logo.url,
        'players': players
    }
    return render(request, 'schools/player_list.html', context)


@school_required()
def create_player_view(request):
    profile = SchoolProfile.objects.filter(user=request.user).first()
    name = profile.name
    logo = profile.logo
    if request.method == "POST":
        form = PlayerForm(request.POST, request.FILES)
        if form.is_valid():
            player = Player.objects.create(
                school=profile,
                passport_photo=form.cleaned_data['passport_photo'],
                national_id=form.cleaned_data['national_id'],
                national_id_image=form.cleaned_data['national_id_image'],
                birth_certificate=form.cleaned_data['birth_certificate'],
                grade_7_result=form.cleaned_data['grade_7_result'],
                first_name=form.cleaned_data['first_name'],
                last_name=form.cleaned_data['last_name'],
                middle_name=form.cleaned_data['middle_name'],
                birth_certificate_number=form.cleaned_data['birth_certificate_number'],
                guardian_name=form.cleaned_data['guardian_name'],
                guardian_relationship=form.cleaned_data['guardian_relationship'],
                guardian_contact=form.cleaned_data['guardian_contact'],
                date_of_birth=form.cleaned_data['date_of_birth'],
                present_school=form.cleaned_data['present_school'],
                year_enrolled=form.cleaned_data['year_enrolled'],
                previous_school=form.cleaned_data['previous_school'],
                cell=form.cleaned_data['cell'],
                position=form.cleaned_data['position']
            )

            player.save()
            return redirect('schools:player_list')
        else:
            messages.error(request, form.errors)

    context = {
        'form': PlayerForm(),
        'name': name,
        'logo': logo.url
    }
    return render(request, 'schools/create_player.html', context)


@school_required()
def player_profile_view(request, id):
    profile = SchoolProfile.objects.filter(user=request.user).first()
    name = profile.name
    logo = profile.logo
    player = Player.objects.filter(id=id).first()
    tournaments= TournamentPlayer.objects.filter(player=player).select_related('tournament')
    played_tournaments = [tp.tournament for tp in tournaments]
    context = {
        'player': player,
        'name': name,
        'logo': logo.url,
        'tournaments': played_tournaments
    }
    return render(request, 'schools/player_profile.html', context)


@school_required()
def register_tournament_view(request, id):
    tournament = Tournament.objects.filter(id=id)
    profile = SchoolProfile.objects.filter(user=request.user).first()
    name = profile.name
    logo = profile.logo
    context = {
        'tournament': tournament,
        'name': name,
        'logo': logo.url
    }
    return render(request, 'schools/tournament_view.html', context)


@school_required()
def tournament_detail_view(request, id):
    profile = SchoolProfile.objects.filter(user=request.user).first()
    name = profile.name
    logo = profile.logo
    tournament = Tournament.objects.filter(id=id).first()
    reg = TournamentRegistration.objects.filter(school=profile, tournament=tournament)
    tournament_players = TournamentPlayer.objects.filter(tournament_id=id, player__school_id=profile.id).select_related('player')
    players = [tp.player for tp in tournament_players]

    if request.method == "POST":
        form = TournamentRegistrationForm(request.POST, request.FILES)
        if form.is_valid():
            tournament_reg = TournamentRegistration.objects.create(
                school=profile,
                tournament=tournament,
                proof_of_payment=form.cleaned_data['proof_of_payment']
            )
            tournament_reg.save()
            return redirect('schools:tournament_detail', tournament.id)
        else:
            messages.error(request, form.errors)

    context = {
        'tournament': tournament,
        'name': name,
        'logo': logo.url,
        'form': TournamentRegistrationForm(),
        'is_registered': reg.exists(),
        'reg': reg.first(),
        'registered_schools': SchoolProfile.objects.filter(tournamentregistration__tournament=tournament),
        'tournament_results': TournamentResults.objects.filter(tournament=tournament),
        'registered_players': players
    }
    return render(request, 'schools/tournament_view.html', context)


def register_players_for_tournament_view(request, tournament_id):
    tournament = get_object_or_404(Tournament, id=tournament_id)
    profile = SchoolProfile.objects.filter(user=request.user).first()
    name = profile.name
    logo = profile.logo

    if request.method == 'POST':
        form = RegisterPlayersForm(request.POST, school=profile, tournament=tournament)
        if form.is_valid():
            players = form.cleaned_data['players']
            for player in players:
                if player.age < tournament.age_limit:
                    TournamentPlayer.objects.create(
                        tournament=tournament,
                        player=player,
                        approved=False

templates/schools/404_page.html
{% extends 'base.html' %}
{% load static %}



{% block content %}

  <body class="light ">
    <div class="wrapper vh-100">
      <div class="align-items-center h-100 d-flex w-50 mx-auto">
        <div class="mx-auto text-center">
          <h1 class="display-1 m-0 font-weight-bolder text-muted" style="font-size:80px;">404</h1>
          <h1 class="mb-1 text-muted font-weight-bold">OOPS!</h1>
          <h6 class="mb-3 text-muted">The page could not be found.</h6>
        </div>
      </div>
    </div>


{% endblock content %}

templates/schools/create_player.html
{% include 'schools/base.html' %}
{% load static %}
{% block title %} {{ name }} {% endblock title %}

{% block content %}

<div class="wrapper">
{% include 'schools/navbar.html' %}
 <main role="main" class="main-content">
        <div class="container-fluid">
          <div class="row justify-content-center">

            <div class="col-12 col-xl-12">
              <h2 class="page-title">Register New Player</h2>
              <p class="text">This form is designed for registering of new players. To ensure the accuracy and effectiveness of your form, please fill out all required fields completely and truthfully as the details submitted will be verified.</p>
              <div class="card-deck">
              </div> <!-- / .card-desk-->
              <div class="row">
                <div class="col-md-12">
                  <div class="card shadow mb-4">
                    <div class="card-header">
                      <strong class="card-title">All fields are required.</strong>
                    </div>
                    <div class="card-body">
                      <form method="post" enctype="multipart/form-data" action="{% url 'schools:create_player' %}">
                          {% csrf_token %}
                          <div class="form-row">
                            <div class="form-group col-md-4">
                            <label for="inputPhone">First Name</label>
                            {{ form.first_name }}
                          </div>
                             <div class="form-group col-md-4">
                            <label for="warradasdnty">Middle Name</label>
                            {{ form.middle_name }}
                          </div>
                              <div class="form-group col-md-4">
                            <label for="warradasdsaasdnty">Surname</label>
                            {{ form.last_name }}
                          </div>
                          </div>
                        <div class="form-row">
                           <div class="form-group col-md-6">
                            <label for="inpusacsactValue">Game Position</label>
                            {{ form.position }}
                          </div>
                          <div class="form-group col-md-6">
                          <label for="inputCondsaacitasdion">Cell</label>
                          {{ form.cell }}
                        </div>
                          </div>
                          <div class="form-row">
                           <div class="form-group col-md-4">
                            <label for="inputValue">Date of Birth</label>
                            {{ form.date_of_birth }}
                          </div>
                          <div class="form-group col-md-4">
                          <label for="inputConditasdion">Nation ID Number</label>
                          {{ form.national_id }}
                        </div>
                            <div class="form-group col-md-4">
                          <label for="inputConcsdition">Birth Certificate Number</label>
                          {{ form.birth_certificate_number }}
                        </div>
                          </div>
                          <div class="form-row">
                           <div class="form-group col-md-6">
                            <label for="inasdputValue">Guardian Full Name</label>
                            {{ form.guardian_name }}
                          </div>
                          <div class="form-group col-md-3">
                          <label for="inpasutConditasdion">Guardian Relationship</label>
                          {{ form.guardian_relationship }}
                        </div>
                            <div class="form-group col-md-3">
                          <label for="inpuasscvtConcsdition">Guardian Contact</label>
                          {{ form.guardian_contact }}
                        </div>
                          </div>

                          <div class="form-row ">
                             <div class="form-group col-md-4">
                            <label for="inputCsaurrency">Present School</label>
                            {{ form.present_school }}
                          </div>
                              <div class="form-group col-md-4">
                            <label for="inputCurrsency">Year Enrolled</label>
                            {{ form.year_enrolled }}
                          </div>
                              <div class="form-group col-md-4">
                            <label for="inputsaCsurrsency">Previous School</label>
                            {{ form.previous_school }}
                          </div>
                          </div>
                        <div class="mt-3 form-row">
                          <div class="form-group col-md-3">
                          <label for="inputRoom">Passport Photo</label>
                          {{ form.passport_photo }}
                        </div>
                          <div class="form-group col-md-3">
                          <label for="inputRoom">National Id</label>
                          {{ form.national_id_image }}
                        </div>
                            <div class="form-group col-md-3">
                          <label for="inputRoom">Birth Certificate</label>
                          {{ form.birth_certificate }}
                        </div>
                         <div class="form-group col-md-3">
                            <label for="warranty">Grade 7 Result Slip</label>
                            {{ form.grade_7_result }}
                          </div>
                        </div>

                        <button type="submit" class="btn btn-primary">Submit Form</button>
                      </form>
                    </div> <!-- /. card-body -->
                  </div> <!-- /. card -->
                </div> <!-- /. col -->
              </div> <!-- /. end-section -->
             </div> <!-- .col-12 -->
          </div> <!-- .row -->
        </div> <!-- .container-fluid -->
      </main>

</div>

{% include 'schools/scripts.html' %}

{% endblock content %}

templates/schools/navbar.html
 {% load static %}

      <nav class="topnav navbar navbar-light">

        <button type="button" class="navbar-toggler text-muted mt-2 p-0 mr-3 collapseSidebar">
          <i class="fe fe-menu navbar-toggler-icon"></i>
        </button>

      </nav>
      <aside class="sidebar-left border-right bg-white shadow" id="leftSidebar" data-simplebar>
        <a href="#" class="btn collapseSidebar toggle-btn d-lg-none text-muted ml-2 mt-3" data-toggle="toggle">
          <i class="fe fe-x"><span class="sr-only"></span></i>
        </a>
        <nav class="vertnav navbar navbar-light">
          <!-- nav bar -->
          <div class="w-100 mb-4 d-flex">
            <a class="navbar-brand mx-auto mt-2 flex-fill text-center" href="{% url 'schools:school_dashboard' %}">
              <img height="120px" src="{{ logo }}">
            </a>
          </div>
          <ul class="navbar-nav flex-fill w-100 mb-2">
            <li class="nav-item">
              <a aria-expanded="false" class="nav-link" href="{% url 'schools:school_dashboard' %}" >
                <i class="fe fe-home fe-16"></i>
                <span class="ml-3 item-text">Dashboard</span><span class="sr-only">(current)</span>
              </a>
            </li>
          </ul>

          <ul class="navbar-nav flex-fill w-100 mb-2">
            <li class="nav-item w-100">
              <a class="nav-link" href="{% url 'schools:upcoming_tournaments' %}">
                <i class="fe fe-monitor fe-16"></i>
                <span class="ml-3 item-text">Upcoming Tournaments</span>
              </a>
            </li>
            <li class="nav-item w-100">
              <a class="nav-link" href="{% url 'schools:registered_tournaments' %}">
                <i class="fe fe-tv fe-16"></i>
                <span class="ml-3 item-text">Registered Tournaments</span>
              </a>
            </li>

              <li class="nav-item w-100">
              <a class="nav-link" href="{% url 'schools:result_list' %}">
                <i class="fe fe-clipboard fe-16"></i>
                <span class="ml-3 item-text">Results List</span>
              </a>
            </li>

              <li class="nav-item w-100">
              <a class="nav-link" href="{% url 'schools:player_list' %}">
                <i class="fe fe-users fe-16"></i>
                <span class="ml-3 item-text">All Players</span>
              </a>
            </li>
{##}
{#          <li class="nav-item w-100">#}
{#              <a class="nav-link" href="{% url 'management:admin_users' %}">#}
{#                <i class="fe fe-log-out fe-16"></i>#}
{#                <span class="ml-3 item-text">Users</span>#}
{#              </a>#}
{#            </li>#}

            <li class="nav-item w-100">
              <a class="nav-link" href="{% url 'schools:school_logout' %}">
                <i class="fe fe-log-out fe-16"></i>
                <span class="ml-3 item-text">Log Out</span>
              </a>
            </li>


          </ul>
        </nav>
      </aside>

templates/schools/register_user.html
{% extends 'schools/base.html' %}
{% load static %}
{% load crispy_forms_tags %}


{% block content %}

<div class="wrapper vh-100">
      <div class="row align-items-center h-100">
        <form class="col-lg-3 col-md-4 col-10 mx-auto text-center" method="POST">
            {% csrf_token %}

{#            <img height="50px" src="{% static 'assets/images/zrplogo1.jpeg' %}">#}
          <h3 class="mt-3 mb-3 title"><strong>Register School Account</strong></h3>

            {{ form | crispy }}

            <button class="btn btn-lg btn-primary btn-block" type="submit">Register Account</button>
            <a href="{% url 'schools:school_login' %}"><button class="btn btn-lg btn-success btn-block mt-3" type="button">Go To Login</button></a>
            <a href="{% url 'core:home' %}"><button class="btn btn-lg btn-dark btn-block mt-3" type="button">Return To Main Site</button></a>
          <p class="mt-5 mb-3 text-muted">© 2024</p>
        </form>
      </div>
    </div>


{% endblock content %}

templates/schools/user_login.html
{% extends 'schools/base.html' %}
{% load static %}
{% load crispy_forms_tags %}


{% block content %}

<div class="wrapper vh-100">
      <div class="row align-items-center h-100">
        <form class="col-lg-3 col-md-4 col-10 mx-auto text-center" method="POST">
            {% csrf_token %}

{#            <img height="60px" src="{% static 'assets/images/zrplogo1.jpeg' %}">#}
          <h1 class="mt-3 mb-3 title"><strong>School Portal Login</strong></h1>

            {{ form | crispy }}

{#          <div class="form-group">#}
{#            <label for="inputEmail" class="sr-only">Email address</label>#}
{#            <input type="email" id="inputEmail" class="form-control form-control-lg" placeholder="Email address" required="" autofocus="">#}
{#          </div>#}
{#          <div class="form-group">#}
{#            <label for="inputPassword" class="sr-only">Password</label>#}
{#            <input type="password" id="inputPassword" class="form-control form-control-lg" placeholder="Password" required="">#}
{#          </div>#}
          <button class="btn btn-lg btn-primary btn-block" type="submit">Log In</button>
            <a href="{% url 'schools:school_register' %}"><button class="btn btn-lg btn-success btn-block mt-3 mb-3" type="button">Register Account</button></a>
            <a href="{% url 'core:home' %}"><button class="btn btn-lg btn-dark btn-block mt-3" type="button">Return To Main Site</button></a>
          <p class="mt-5 mb-3 text-muted">© 2024</p>
        </form>
      </div>
    </div>


{% endblock content %}